version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps(server)"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps(client)"
